import { useState, useEffect } from 'react';
import './index.css';
import { useStore, applyColorMode, loadPhotosFromServer } from './store';
import DumpCard from './components/DumpCard';
import PhotoPool from './components/PhotoPool';
import CaptionPool from './components/CaptionPool';
import Lightbox from './components/Lightbox';
import { InstallPrompt } from './components/InstallPrompt';
import { Onboarding } from './components/Onboarding';
import { SettingsPanel } from './components/SettingsPanel';

// ─── Splash Screen ────────────────────────────────────────────────────────────
function SplashScreen({ onDone }: { onDone: () => void }) {
  const [phase, setPhase] = useState<'in' | 'hold' | 'out'>('in');

  useEffect(() => {
    const t1 = setTimeout(() => setPhase('hold'), 600);
    const t2 = setTimeout(() => setPhase('out'), 2200);
    const t3 = setTimeout(onDone, 2800);
    return () => { clearTimeout(t1); clearTimeout(t2); clearTimeout(t3); };
  }, [onDone]);

  return (
    <div
      onClick={onDone}
      style={{
        position: 'fixed', inset: 0, zIndex: 9999,
        background: '#0a0a0a',
        display: 'flex', flexDirection: 'column',
        alignItems: 'center', justifyContent: 'center',
        gap: 20,
        opacity: phase === 'out' ? 0 : 1,
        transition: phase === 'out' ? 'opacity 0.6s cubic-bezier(0.16, 1, 0.3, 1)' : 'none',
        cursor: 'pointer',
      }}
    >
      {/* Logo icon */}
      <div style={{
        opacity: phase === 'in' ? 0 : 1,
        transform: phase === 'in' ? 'scale(0.7)' : 'scale(1)',
        transition: 'opacity 0.6s cubic-bezier(0.16, 1, 0.3, 1), transform 0.6s cubic-bezier(0.16, 1, 0.3, 1)',
      }}>
        <DumpsterLogo size={72} />
      </div>
      {/* Wordmark */}
      <div style={{
        opacity: phase === 'in' ? 0 : 1,
        transform: phase === 'in' ? 'translateY(12px)' : 'translateY(0)',
        transition: 'opacity 0.5s 0.15s cubic-bezier(0.16, 1, 0.3, 1), transform 0.5s 0.15s cubic-bezier(0.16, 1, 0.3, 1)',
        textAlign: 'center',
      }}>
        <p style={{
          fontSize: 36, fontWeight: 800, letterSpacing: '0.18em',
          color: '#C8A96E', fontFamily: "'Inter', sans-serif",
          textTransform: 'uppercase',
        }}>DUMPSTER</p>
        <p style={{
          fontSize: 11, letterSpacing: '0.22em', color: 'rgba(200,169,110,0.45)',
          fontFamily: "'Inter', sans-serif", fontWeight: 500,
          textTransform: 'uppercase', marginTop: 6,
        }}>Build Your Dumps</p>
      </div>
    </div>
  );
}

export default function App() {
  const {
    dumps, photos, activeDumpId, colorMode,
    newDump, autoGenerateDump, setActiveDump, undo, redo, canUndo, canRedo,
  } = useStore();

  const [showSplash, setShowSplash] = useState(true);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [autoPickerOpen, setAutoPickerOpen] = useState(false);
  const [autoCount, setAutoCount] = useState(7);
  const [showOnboarding, setShowOnboarding] = useState(false);
  const [activePool, setActivePool] = useState<'photos' | 'captions'>('photos');
  const usedIds = new Set(dumps.flatMap((d) => d.photos));
  const usedCount = usedIds.size;
  const poolCount = photos.filter((p) => !usedIds.has(p.id)).length;

  // Apply color mode on load
  useEffect(() => {
    applyColorMode(colorMode);
    const mq = window.matchMedia('(prefers-color-scheme: dark)');
    const handler = () => { if (colorMode === 'system') applyColorMode('system'); };
    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  }, [colorMode]);

  // Load server photos if pool is empty
  useEffect(() => {
    if (photos.length === 0) loadPhotosFromServer();
  }, []);

  // Show onboarding on first visit
  useEffect(() => {
    const completed = localStorage.getItem('onboardingCompleted');
    if (!completed && dumps.length === 0) {
      setShowOnboarding(true);
    }
  }, [dumps.length]);

  // Keyboard undo/redo
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'z') {
        e.preventDefault();
        if (e.shiftKey) redo(); else undo();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [undo, redo]);

  return (
    <div style={{ background: 'var(--bg)', minHeight: '100vh' }}>
      {showSplash && <SplashScreen onDone={() => setShowSplash(false)} />}
      {settingsOpen && (
        <SettingsPanel
          onClose={() => setSettingsOpen(false)}
          onOpenTutorial={() => { setShowOnboarding(true); setSettingsOpen(false); }}
        />
      )}
      <Lightbox />
      <InstallPrompt />
      {showOnboarding && <Onboarding onComplete={() => setShowOnboarding(false)} />}
      <div style={{ maxWidth: 1100, margin: '0 auto', padding: '0 32px' }}>

        {/* ── Header ──────────────────────────────────────── */}
        <header style={{ paddingTop: 52, paddingBottom: 36 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
              <DumpsterLogo size={22} />
              <p style={{
                fontSize: 11, letterSpacing: '0.18em', color: 'var(--gold)',
                textTransform: 'uppercase', fontWeight: 700,
              }}>DUMPSTER</p>
            </div>

            {/* Top-right controls */}
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              {/* Undo / Redo */}
              <button
                onClick={undo} disabled={!canUndo()}
                title="Undo (⌘Z)"
                style={undoRedoStyle(!canUndo())}
              >←</button>
              <button
                onClick={redo} disabled={!canRedo()}
                title="Redo (⌘⇧Z)"
                style={undoRedoStyle(!canRedo())}
              >→</button>

              {/* Settings hamburger */}
              <button
                onClick={() => setSettingsOpen(true)}
                style={{
                  width: 36, height: 36, borderRadius: 8,
                  background: 'var(--bg2)', border: '1px solid var(--border2)',
                  cursor: 'pointer', display: 'flex', flexDirection: 'column',
                  alignItems: 'center', justifyContent: 'center', gap: 4,
                }}
              >
                {[0, 1, 2].map(i => (
                  <div key={i} style={{ width: 14, height: 1.5, borderRadius: 1, background: 'var(--text3)' }} />
                ))}
              </button>
            </div>
          </div>

          <h1 style={{
            fontSize: 52, fontWeight: 800, color: 'var(--text)', lineHeight: 1.05,
            marginBottom: 14, letterSpacing: '-0.02em',
          }}>
            Build Your{' '}
            <span style={{ color: 'var(--gold)' }}>Dumps</span>
          </h1>
          <p style={{ fontSize: 14, color: 'var(--text3)', lineHeight: 1.6, marginBottom: 28, maxWidth: 560 }}>
            Double-tap a photo to enlarge. Drag to reorder. Tap + to add from the pool.
          </p>
          <div style={{ display: 'flex', gap: 8 }}>
            <StatPill num={dumps.length} label="Dumps" />
            <StatPill num={usedCount} label="Photos Used" />
            <StatPill num={poolCount} label="In Pool" />
          </div>
        </header>

        <div style={{ borderTop: '1px solid var(--border2)', marginBottom: 48 }} />

        {/* ── Dump Cards ───────────────────────────────────── */}
        <div style={{ overflow: 'hidden', position: 'relative', zIndex: 1 }}>
          {dumps.map((dump) => (
            <DumpCard
              key={dump.id}
              dump={dump}
              active={dump.id === activeDumpId}
              onActivate={() => setActiveDump(dump.id)}
            />
          ))}
        </div>

        {/* ── Actions ──────────────────────────────────────── */}
        <div style={{ display: 'flex', gap: 10, marginBottom: 72, marginTop: 8, alignItems: 'flex-start' }}>
          <ActionButton icon="+" label="New Dump" onClick={newDump} />

          {/* Auto-Generate button + count picker */}
          <div style={{ position: 'relative' }}>
            <ActionButton
              icon="⚡"
              label="Auto-Generate"
              onClick={() => setAutoPickerOpen(o => !o)}
              gold
            />
            {autoPickerOpen && (
              <div className="menu-dropdown" style={{
                position: 'absolute', top: '110%', left: 0, zIndex: 50,
                background: 'var(--menu-bg)', border: '1px solid var(--border2)',
                borderRadius: 12, padding: 16, minWidth: 200,
                backdropFilter: 'blur(16px)', WebkitBackdropFilter: 'blur(16px)',
              }}>
                <p style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', color: 'var(--gold)', textTransform: 'uppercase', marginBottom: 10 }}>
                  Photos to pick
                </p>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
                  <button
                    onClick={() => setAutoCount(c => Math.max(2, c - 1))}
                    style={{ width: 28, height: 28, borderRadius: 6, background: 'var(--bg2)', border: '1px solid var(--border2)', color: 'var(--text)', fontSize: 16, cursor: 'pointer' }}
                  >−</button>
                  <span style={{ fontSize: 22, fontWeight: 700, color: 'var(--text)', minWidth: 32, textAlign: 'center' }}>{autoCount}</span>
                  <button
                    onClick={() => setAutoCount(c => Math.min(20, c + 1))}
                    style={{ width: 28, height: 28, borderRadius: 6, background: 'var(--bg2)', border: '1px solid var(--border2)', color: 'var(--text)', fontSize: 16, cursor: 'pointer' }}
                  >+</button>
                  <span style={{ fontSize: 10, color: 'var(--text3)' }}>of {poolCount} available</span>
                </div>
                <button
                  onClick={() => { autoGenerateDump(autoCount); setAutoPickerOpen(false); }}
                  disabled={poolCount === 0}
                  style={{
                    width: '100%', padding: '9px 0', borderRadius: 8,
                    background: poolCount === 0 ? 'var(--bg2)' : 'var(--gold-dim)',
                    border: `1px solid ${poolCount === 0 ? 'var(--border2)' : 'rgba(200,169,110,0.4)'}`,
                    color: poolCount === 0 ? 'var(--text3)' : 'var(--gold)',
                    fontSize: 12, fontWeight: 700, letterSpacing: '0.06em', cursor: poolCount === 0 ? 'not-allowed' : 'pointer',
                  }}
                >
                  {poolCount === 0 ? 'No photos in pool' : 'Generate Dump'}
                </button>
              </div>
            )}
          </div>
        </div>

        <div style={{ borderTop: '1px solid var(--border2)', marginBottom: 48 }} />

        {/* ── Pool Toggle ──────────────────────────────────── */}
        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 32 }}>
          <div style={{
            display: 'flex', width: 260, height: 40,
            borderRadius: 20, background: 'var(--bg2)',
            border: '1px solid var(--border2)', position: 'relative',
            overflow: 'hidden', cursor: 'pointer',
          }}>
            {/* Sliding pill */}
            <div style={{
              position: 'absolute', top: 3, bottom: 3,
              width: '50%', borderRadius: 17,
              background: 'var(--gold-dim)', border: '1px solid rgba(200,169,110,0.3)',
              transition: 'transform 0.35s cubic-bezier(0.16, 1, 0.3, 1)',
              transform: activePool === 'photos' ? 'translateX(3px)' : 'translateX(calc(100% - 3px))',
            }} />
            <button
              onClick={() => setActivePool('photos')}
              style={{
                flex: 1, zIndex: 1, background: 'transparent', border: 'none',
                fontSize: 11, fontWeight: 700, letterSpacing: '0.08em',
                color: activePool === 'photos' ? 'var(--gold)' : 'var(--text3)',
                cursor: 'pointer', transition: 'color 0.2s',
                textTransform: 'uppercase', fontFamily: 'var(--font)',
              }}
            >Photos</button>
            <button
              onClick={() => setActivePool('captions')}
              style={{
                flex: 1, zIndex: 1, background: 'transparent', border: 'none',
                fontSize: 11, fontWeight: 700, letterSpacing: '0.08em',
                color: activePool === 'captions' ? 'var(--gold)' : 'var(--text3)',
                cursor: 'pointer', transition: 'color 0.2s',
                textTransform: 'uppercase', fontFamily: 'var(--font)',
              }}
            >Captions</button>
          </div>
        </div>

        {/* ── Photo Pool / Caption Pool ──────────────────── */}
        <div className="pool-section" key={activePool} style={{ position: 'relative', zIndex: 2 }}>
          {activePool === 'photos' ? <PhotoPool /> : <CaptionPool />}
        </div>

        <div style={{ height: 80 }} />
      </div>
    </div>
  );
}

// ─── Logo ─────────────────────────────────────────────────────────────────────

function DumpsterLogo({ size = 32 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
      {/* Trash can body */}
      <rect x="7" y="14" width="26" height="22" rx="3" fill="none" stroke="#C8A96E" strokeWidth="2"/>
      {/* Lid */}
      <rect x="4" y="10" width="32" height="5" rx="2" fill="none" stroke="#C8A96E" strokeWidth="2"/>
      {/* Handle */}
      <path d="M15 10V8a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v2" stroke="#C8A96E" strokeWidth="2" strokeLinecap="round"/>
      {/* Lines inside */}
      <line x1="14" y1="20" x2="14" y2="30" stroke="#C8A96E" strokeWidth="1.5" strokeLinecap="round"/>
      <line x1="20" y1="20" x2="20" y2="30" stroke="#C8A96E" strokeWidth="1.5" strokeLinecap="round"/>
      <line x1="26" y1="20" x2="26" y2="30" stroke="#C8A96E" strokeWidth="1.5" strokeLinecap="round"/>
    </svg>
  );
}

// ─── helpers ─────────────────────────────────────────────────────────────────

function undoRedoStyle(disabled: boolean): React.CSSProperties {
  return {
    width: 32, height: 32, borderRadius: 6, fontSize: 14, fontWeight: 700,
    background: 'var(--bg2)', border: '1px solid var(--border2)',
    color: disabled ? 'var(--border3)' : 'var(--text2)',
    cursor: disabled ? 'default' : 'pointer',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    transition: 'all 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
    opacity: disabled ? 0.4 : 1,
    transform: 'scale(1)',
  };
}

function StatPill({ num, label }: { num: number; label: string }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 6,
      background: 'var(--bg2)', border: '1px solid var(--border2)',
      borderRadius: 999, padding: '6px 14px',
    }}>
      <span style={{ fontSize: 13, fontWeight: 700, color: 'var(--text)' }}>{num}</span>
      <span style={{ fontSize: 12, color: 'var(--text3)' }}>{label}</span>
    </div>
  );
}

function ActionButton({ icon, label, onClick, gold }: { icon: string; label: string; onClick: () => void; gold?: boolean }) {
  return (
    <button
      onClick={onClick}
      style={{
        display: 'flex', alignItems: 'center', gap: 6,
        background: gold ? 'var(--gold-dim)' : 'var(--bg2)',
        border: `1px solid ${gold ? 'rgba(200,169,110,0.4)' : 'var(--border2)'}`,
        borderRadius: 8, padding: '10px 18px',
        color: gold ? 'var(--gold)' : 'var(--text2)',
        fontSize: 13, fontWeight: 500, transition: 'all 0.15s',
      }}
      onMouseEnter={(e) => {
        (e.currentTarget as HTMLButtonElement).style.borderColor = 'var(--gold)';
        (e.currentTarget as HTMLButtonElement).style.color = 'var(--gold)';
      }}
      onMouseLeave={(e) => {
        (e.currentTarget as HTMLButtonElement).style.borderColor = gold ? 'rgba(200,169,110,0.4)' : 'var(--border2)';
        (e.currentTarget as HTMLButtonElement).style.color = gold ? 'var(--gold)' : 'var(--text2)';
      }}
    >
      <span style={{ fontSize: 15 }}>{icon}</span>
      {label}
    </button>
  );
}
